### ISSUE TITLE
Backtest: Annualized return and Sharpe ratio are wrong for non-daily granularity

### ISSUE THREAD

**Issue by alexander-gr** [santiment/sanpy#104]
365 days are hardcoded [here](https://github.com/santiment/sanpy/blob/master/san/extras/backtest.py#L43) and [here](https://github.com/santiment/sanpy/blob/master/san/extras/backtest.py#L69)

**Comment by JanSmirny** [comment]
@alexander-gr Yes true. How could we improve that? Pandas has a function to infer the granularity of the data `pd.infer_freq(data.index)`. Output would be `"D"`. So we could do a bunch of conditions. If "D" then * 365, if "H" then * 365 * 24. But that only works if the entered time series has a datetime index... 

Any better ideas?

**Comment by valo** [comment]
Should we count the number of intervals for an year and use that? So take `self.strategy_returns` and see how many data points per year it contains.

**Comment by JanSmirny** [comment]
But in that case we might run into problems if we use less than a years worth of data for the backtest.

**Comment by alexander-gr** [comment]
Backtest will be refactored soon. Closing the issue
