### ISSUE TITLE
14-day trial API key not recognised

### ISSUE THREAD

**Issue by phisanti** [santiment/sanpy#140]
I have been toying around with SAN API and now I wanted to try some models with up-to-date data. For that, I tried to get a 14-trial Pro account. However, when I try to retrieve data from the last month or older than 2y, I still get the error:

```python
 "parameters are outside the allowed interval you can query exchange_outflow_usd with your current subscription SANAPI free. Upgrade to a higher tier in order to access more data."

```
Does it mean that the 14-days free trial does not include the API keys usage?

**Comment by IvanIvanoff** [comment]
The trial does not include direct API access, but only PRO access to the website https://app.santiment.net
