### ISSUE TITLE
Screener call

### ISSUE THREAD

**Issue by phisanti** [santiment/sanpy#141]
I was wondering if there is any function, even if it is ray graphQL, to call the screener that we can use through the web interface.

**Comment by IvanIvanoff** [comment]
Hi @phisanti,

The library's intended use is to call the metrics, so for the rest of the functionality, there is no function implemented.
But if you know the GraphQL request you want to execute you can do the following, as described [here](https://github.com/santiment/sanpy#making-a-custom-graphql-query-to-the-api):
```python
from san.graphql import execute_gql
metrics = execute_gql("""
{
  watchlist(id: 5296) {
    listItems {
      project {
        id
        name
        slug
        ticker
      }
    }
  }
}
""")
```
