### ISSUE TITLE
Please remove user warning when library is out of date

### ISSUE THREAD

**Issue by pmantica3** [santiment/sanpy#152]
Thanks for the awesome work on this library. It really makes interacting with santiment easier. I have a suggestion though that I could make the user experience slightly better.

I am getting the following user warning:
```/home/ubuntu/.local/lib/python3.10/site-packages/san/__init__.py:31: UserWarning: The package sanpy is out of date. Your version is 0.10.1, the latest is 0.10.2.```

I don't think that it's a good idea to warn when a python package is out of date. I use 100 hundreds of python packages. If I would get a warning when the patch version of each package is out of date, then I would be flooded by user warnings. So maybe you can emit a warning there has been a breaking change and the major version is out of date instead?

**Comment by IvanIvanoff** [comment]
Closed by https://github.com/santiment/sanpy/pull/153
